Use Vite builder
editor-js/create-tool pull request #10
Opened 2022-11-21 16:25 UTC by talyguryn

resolves #4
resolves #9

2022-11-29 19:35 UTC, robonetphy requested changes
Also, can you add the instructions to test the `create-tool` locally in `README.md`..
https://github.com/editor-js/create-tool/blob/d05359e6066b9ccc534e5d6ec730dbe2cf9979cf/bin/create-tool.js#L5
Also, Pls remove this line since it's not useful.

2022-11-29 21:14 UTC, talyguryn commented on package.json
>    "main": "index.js",
need to remove `main` i think

2022-11-29 22:37 UTC, ilyamore88 commented on template/vite.config.js
> +  if (command === 'build') return {
Do you need to check the command here? As I see, you're setting up only parameters for the build. So, you can just export an object, not a function.

2022-11-29 22:39 UTC, ilyamore88 commented on template/package.json
> +    "@codexteam/icons": "^0.0.4",
Are you sure that this is a dev dep too?

2022-11-29 22:44 UTC, ilyamore88 commented on template/vite.config.js
> +        },
Could you use build.lib for this?
https://vitejs.dev/config/build-options.html#build-lib

2022-11-29 22:59 UTC, ilyamore88 commented on template/vite.config.js
> +        preserveEntrySignatures: 'strict',
Why do you need this parameter? It's not very clear to me from the documentation. Are you using it so that there is only one export in the index file?

2022-11-30 10:47 UTC, talyguryn commented on template/package.json
> +    "@codexteam/icons": "^0.0.4",
yes. result bundle in `dist` dir has no deps

2022-11-30 10:48 UTC, talyguryn commented on template/vite.config.js
> +  if (command === 'build') return {
i use fallback below for dev run

![image](https://user-images.githubusercontent.com/15259299/204776479-92e721af-4b44-4162-a6cf-f8066f616d50.png)

2022-11-30 10:56 UTC, ilyamore88 commented on template/vite.config.js
> +  if (command === 'build') return {
Yep, I see, but build field is used for vite build only. And server field is used for vite dev. It'll work just like:
```js
export default {
  build: // build settings,
  server: // vite dev settings,
}
```

2022-11-30 12:14 UTC, ilyamore88 commented on template/vite.config.js
> +      fileName: () => 'VAR_TOOL_NAME.js'
```suggestion
      fileName: 'VAR_TOOL_NAME.js',
```

2022-11-30 14:03 UTC, robonetphy approved these changes

2022-11-30 18:14 UTC, merged